### ISSUE TITLE
Gracefully skip nightly releases when credentials aren't present

### ISSUE THREAD

**Issue by hectormz** [aesara-devs/aesara#954]
## Description of your problem or feature request

My `main` branch of my fork of `aesara` runs a nightly build via GitHub Actions, and fails each night because I don't have the secrets/credentials. I get a notification of the failed Action every night, and assume this happens for others too.

Can we change the GitHub Action to disable this? I think two options would be to either skip the build if the secret credentials are not found, or to check if it is run on the main `aesara-devs` copy.

**Comment by brandonwillard** [comment]
Actions can be disabled at the repo level; this is what I've done for mine.

Aside from that, small updates to the Actions workflow that help with this are welcome.

**Comment by hectormz** [comment]
TIL individual workflows can be disabled!

Up to you if you want to consider any of the changes to the workflows.

**Comment by hectormz** [comment]
Perhaps the easiest thing would be:

```
jobs:
  build_and_publish:
    name: Build source distribution
    if: github.repository == 'aesara-devs/aesara'
    runs-on: ubuntu-latest
```

That way it will still fail if something happens to the org secrets. And building nightly and pushing to Pypi should only come from this account anyway.

I just tested this on my main with a "Nightly" action that runs on push.
